version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/fuzzer"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/instrumentor"
    schedule:
      interval: "daily"
