version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    ignore:
      - dependency-name: "yargs"
        versions:
          - ">=18.0.0"
    groups:
      minor-dependencies:
        update-types:
          - "minor"
          - "patch"
