version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    groups:
      minor-dependencies:
        update-types:
          - "minor"
          - "patch"
