name: Datadog Event

on:
  release:
    types: [published]

jobs:
  send-release-event:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Event
        run: |
          curl -sX POST "https://api.datadoghq.eu/api/v1/events" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            --data-raw '{
              "title": "Jazzer.js has been released",
              "text": "%%% \nJazzer.js has been released with version **${{ github.event.release.tag_name }}**\n %%%",
              "tags": [
                "repo:${{ github.repository }}",
                "project:Jazzer.js",
                "version:${{ github.event.release.tag_name }}"
              ]
            }'
