name: automerge

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          target: minor
          merge-method: rebase
          github-token: ${{ secrets.GITHUB_TOKEN }}
