name: "🔍 Fuzz Tests"
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  fuzz_tests:
    name: fuzz tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - uses: actions/cache@v5
        id: cache-fuzzer
        with:
          path: |
            packages/fuzzer/prebuilds
          key:
            fuzzer-cache-${{ runner.os }}-${{
            hashFiles('packages/fuzzer/CMakeLists.txt',
            'packages/fuzzer/**/*.h', 'packages/fuzzer/**/*.cpp') }}
      - name: node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: build fuzzer
        if: ${{ steps.cache-fuzzer.outputs.cache-hit != 'true' }}
        run: npm run build --workspace=@jazzer.js/fuzzer
      - name: run all fuzz tests
        run: node fuzztests/runFuzzTests.js
